-- MySQL Script generated by MySQL Workbench
-- Mon Aug 23 23:45:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema parcialdds
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `parcialdds` ;

-- -----------------------------------------------------
-- Schema parcialdds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parcialdds` DEFAULT CHARACTER SET utf8 ;
USE `parcialdds` ;

-- -----------------------------------------------------
-- Table `parcialdds`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcialdds`.`Usuario` (
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `idUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcialdds`.`Socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcialdds`.`Socio` (
  `tieneLibroAlquilado` TINYINT NOT NULL,
  `libroAlquilado` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tieneLibroAlquilado`),
  CONSTRAINT `nombre`
    FOREIGN KEY (`usuario`)
    REFERENCES `parcialdds`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `nombre_idx` ON `parcialdds`.`Socio` (`usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `parcialdds`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcialdds`.`Libro` (
  `estaAlquilado` TINYINT(1) NOT NULL,
  `reservado` TINYINT(1) NOT NULL,
  `hayStock` TINYINT(1) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `cantidadStock` INT NOT NULL,
  `valor` INT NOT NULL,
  `clase` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `rentador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `socio`
    FOREIGN KEY (`rentador`)
    REFERENCES `parcialdds`.`Socio` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `socio_idx` ON `parcialdds`.`Libro` (`rentador` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `parcialdds`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcialdds`.`Autor` (
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `librosCreados` VARCHAR(45) NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY (`librosCreados`)
    REFERENCES `parcialdds`.`Libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcialdds`.`Clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcialdds`.`Clase` (
  `Clase` VARCHAR(45) NOT NULL,
  `Clasecol` VARCHAR(45) NULL,
  PRIMARY KEY (`Clase`),
  CONSTRAINT `clase`
    FOREIGN KEY (`Clase`)
    REFERENCES `parcialdds`.`Libro` (`clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcialdds`.`SuperLibro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcialdds`.`SuperLibro` (
  `idSuperLibro` INT NOT NULL,
  `libros` INT NOT NULL,
  PRIMARY KEY (`idSuperLibro`),
  CONSTRAINT `libros`
    FOREIGN KEY (`libros`)
    REFERENCES `parcialdds`.`Libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `libros_idx` ON `parcialdds`.`SuperLibro` (`libros` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
